---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-argocd-k8-app
  namespace: jenkins
  labels: argocd-k8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-k8-app
  template:
    metadata:
    name: argocd-k8-app-pod
    labels:
      app: argocd-k8-app
  spec:
    containers:
    - name: argocd-k8-app-container
      image: venu1322/cicd-jenkins-argocd-k8:22
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-argo-k8-app
  namespace: jenkins
spec:
  type: NodePort
  selector::
    app: argocd-k8-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006 
      protocol: TCP
  


      
